feat(tvos): add apple tv support

diff --git a/e2e/install_apps b/e2e/install_apps
--- a/e2e/install_apps
+++ b/e2e/install_apps
@@ -10,12 +10,14 @@ set -eu
 [ "$(basename "$PWD")" = "e2e" ] || { echo "must be run from e2e directory" && exit 1; }
 
 platform="${1:-}"
-if [ "$platform" != "android" ] && [ "$platform" != "ios" ]; then
-	echo "usage: $0 <android|ios>"
+if [ "$platform" != "android" ] && [ "$platform" != "ios" ] && [ "$platform" != "tvos" ]; then
+	echo "usage: $0 <android|ios|tvos>"
 	exit 1
 fi
 
-command -v adb >/dev/null 2>&1 || { echo "adb is required" && exit 1; }
+if [ "$platform" = "android" ]; then
+	command -v adb >/dev/null 2>&1 || { echo "adb is required" && exit 1; }
+fi
 
 for file in ./apps/*; do
 	filename="$(basename "$file")"
@@ -24,7 +26,7 @@ for file in ./apps/*; do
 	if [ "$platform" = android ] && [ "$extension" = "apk" ]; then
 		echo "install $filename"
 		adb install -r "$file" >/dev/null || echo "adb: could not install $filename"
-	elif [ "$platform" = ios ] && [ "$extension" = "app" ] && [ "$(uname)" = "Darwin" ]; then
+	elif { [ "$platform" = ios ] || [ "$platform" = tvos ]; } && [ "$extension" = "app" ] && [ "$(uname)" = "Darwin" ]; then
 		echo "install $filename"
 		xcrun simctl install booted "$file" || echo "xcrun: could not install $filename"
 	fi
